apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-catalog-config-cm
  namespace: presto
  labels:
    app: presto-coordinator
data:
  hive.properties: |-
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://10.10.1.128:9083
    hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
  mysql.properties: |-
    connector.name=mysql
    connection-url=jdbc:mysql://10.10.1.203:30306
    connection-user=root
    connection-password=Qloud@dev?123
  cassandra.properties: |-
    connector.name=cassandra
    cassandra.contact-points=10.10.1.116